apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubia
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubia 
  serviceName: "kubia"
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kubia
        image: luksa/kubia-pet
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: data
          mountPath: /var/data
        env:
          - 
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: "fast"
      resources:
        requests:
          storage: 1Mi
      accessModes: [ "ReadWriteOnce" ]