apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia-container
        image: "art.local:8081/docker-local/kubia:1.0"
        ports:
        - containerPort:  8080