apiVersion: v1
kind: Pod
metadata:
  name: "kubia-pod"
  namespace: default
  labels:
    app: "kubia"
spec:
  containers:
  - name: kubia-container
    image: "art.local:8081/docker-local/kubia:1.0"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
    ports:
    - containerPort:  8080
      protocol: TCP
  restartPolicy: Always