apiVersion: v1
kind: Pod
metadata:
  name: "config-map-pod"
  namespace: default
  labels:
    app: "config-map-pod"
spec:
  containers:
  - name: config-map-pod
    image: "busybox"
    command: ["/bin/sh", "-c", "env"]
    envFrom: 
    - configMapRef:
        name: appvar
  restartPolicy: Never