apiVersion: v1
kind: Pod
metadata:
  name: "busy33"
  namespace: default
  labels:
    app: "busy33"
spec:
  dnsPolicy: ClusterFirstWithHostNet
  hostname: busy33
  containers:
  - name: busy-container
    image: "busybox:1.28"
    command: ["sleep", "3600"]
   