apiVersion: v1
kind: Pod
metadata:
  name: "hostpath-pod"
  namespace: default
  labels:
    app: "hostpath-pod"
spec:
  containers:
  - name: test-container
    image: "busybox:1.28.3"
    command: ["sh", "-c", "sleep 300"]
    volumeMounts:
    - name: myhostpath
      mountPath: /workspace
  volumes:
    - name: myhostpath
      hostPath:
        path: /root/workspace/data/volumns/hostpath
        type: DirectoryOrCreate