apiVersion: v1
kind: Pod
metadata:
  name: "nfs-pod"
  namespace: default
  labels:
    app: "nfs-pod"
spec:
  containers:
  - name: test-container
    image: "busybox:1.28.3"
    command: ["sh", "-c", "sleep 300"]
    volumeMounts:
    - name: nfs-volumn
      mountPath: /workspace/html
  volumes:
    - name: nfs-volumn
      nfs:
        server: master
        path: /nfsdata
        ReadOnly: false
  restartPolicy: Always