apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
  namespace: default
  labels:
    name: pv-demo
spec:
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfsdata
    server: master