apiVersion: v1
kind: Pod
metadata:
  name: "test-pod"
  namespace: default
  labels:
    app: "test-pod"
spec:
  containers:
  - name: test-container
    image: "busybox:1.28.3"
    command: 
      - "/bin/sh"
    args:
      - "-c"
      - "touch /workspace/SUCCESS && exit 0 || exit 1"
    volumeMounts:
    - name: nfs-pvc
      mountPath: /workspace
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: pvc-demo
  restartPolicy: Never