apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: default
  labels:
    app: pvc-demo
spec:
  selector:
    matchLabels:
      name: pv-demo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi