apiVersion: v1
kind: Pod
metadata:
  name: "fortune"
  namespace: default
spec:
  containers:
  - name: html-generator
    image: "art.local:8081/docker-local/fortune:1.0"
    resources:
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - name: web-server
    image: nginx:alpine
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    ports:
      - containerPort: 80
        protocol: TCP
  volumes:
    - name: html
      emptyDir: {}