# version 0.0.1
FROM centos:7.9.2009
ENV REFRESHED_AT 2014-06-01
RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
RUN yum install -y yum-utils device-mapper-persistent-data lvm2 wget java git
ADD ./docker-ce.repo /etc/yum.repos.d/docker-ce.repo
RUN yum install docker-ce-19.03.11 -y
# env config
ENV JENKINS_HOME /opt/jenkins/data
ENV JENKINS_MIRROR http://mirrors.jenkins-ci.org
# 
RUN mkdir -p ${JENKINS_HOME}/plugins
RUN mkdir -p /opt/jenkins/
#RUN wget -P /opt/jenkins/jenkins.war ${JENKINS_MIRROR}/war/latest/jenkins.war
COPY jenkins.war /opt/jenkins/

RUN for plugin in chucknorris greenballs scm-api git-client git ws-cleanup cloudbees-bitbucket-branch-source \
        cloudbees-credentials cloudbees-deployer-plugin cloudbees-devoptics-enabler cloudbees-enabler \
        cloudbees-enterprise-plugins cloudbees-feature-management cloudbees-folder 	cloudbees-jenkins-advisor cloudbees-plugin-gateway cloudbees-registration ;\
        do wget -P ${JENKINS_HOME}/plugins/${plugin}/latest/${plugin}.hpi \
        ${JENKINS_MIRROR}/plugins/${plugin}/latest/${plugin}.hpi ;\
    done
#RUN wget -P ${JENKINS_HOME}/plugins/cloudbees-folder/latest/cloudbees-folder.hpi http://mirrors.jenkins-ci.org/plugins/cloudbees-folder/latest/cloudbees-folder.hpi
# 
ADD ./dockerjenkins.sh /usr/local/bin/dockerjenkins.sh
RUN chmod +x /usr/local/bin/dockerjenkins.sh

VOLUME [ "/var/lib/docker" ]

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/dockerjenkins.sh"]