# version 0.0.1
FROM ubuntu:14.04
LABEL jAMES="tURNBULL james@example.com"
RUN apt-get update && apt-get install -y nginx
RUN echo 'Hi, Iam in your container' > /usr/share/nginx/html/index.html
EXPOSE 80
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]