# version 0.0.1
FROM jenkins/jenkins:lts
ENV REFRESHED_AT 2014-06-01
USER root
RUN apt-get -qq update && apt-get install -qq sudo wget
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
#RUN wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.11.tgz
RUN wget http://get.docker.com/builds/Linux/x86_64/docker-latest.tgz
RUN tar -xvzf docker-latest.tgz
RUN mv docker/* /usr/bin/
USER root
RUN /usr/local/bin/install-plugins.sh junit git git-client ssh-slaves greenballs chucknorris ws-cleanup