apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  completions: 5
  template:
    spec:
      containers:
      - name: hello
        image: registry.cn-beijing.aliyuncs.com/qingfeng666/nginx:latest
        command: ['sh', '-c', 'echo "Hello, Kubernetes! " && sleep 1']
      restartPolicy: OnFailure