apiVersion: v1
kind: Pod
metadata:
  name: lifecycle
  labels:
    name: lifecycle
spec:
  containers:
  - name: lifecycle
    image: registry.cn-beijing.aliyuncs.com/qingfeng666/nginx:latest
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c","echo lifecycle from postStart handle > /usr/share/message "]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
