apiVersion: v1
kind: Pod
metadata:
  name: "mongodb"
  namespace: default
spec:
  containers:
  - name: mongodb
    image: "mongo:4.4-focal"
    resources:
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
      - containerPort: 27017
        protocol: TCP
  volumes:
    - name: mongodb-data
      nfs:
        path: /nfsdata
        server: master