apiVersion: v1
kind: Pod
metadata:
  name: "fortune-configmap-volume"
  namespace: default
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    resources:
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d
        readOnly: true
    ports:
      - containerPort: 80
        protocol: TCP
  volumes:
    - name: config
      configMap:
        name: fortune-config