apiVersion: v1
kind: Pod
metadata:
  name: "kubia-manual"
  namespace: default
  labels:
    run: "kubia-manual"
spec:
  containers:
  - name: kubia-container
    image: "art.local:8081/docker-local/kubia:1.0"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  8080
      protocol: TCP
  restartPolicy: Always