apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
  namespace: default
  labels:
    app: batch-job
spec:
  template:
    metadata:
      name: batch-job
      labels:
        app: batch-job
    spec:
      containers:
      - name: batch-job
        image: luksa/batch-job
      restartPolicy: OnFailure