apiVersion: v1
kind: Pod
metadata:
  name: "fortune-env-from-config"
  namespace: default
spec:
  containers:
  - name: fortune-container
    image: "luksa/fortune:env"
    resources:
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    env:
    - name: INTERVA L
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
          optional: true
  - name: web-server
    image: nginx:alpine
    resources:
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    ports:
      - containerPort: 80
        protocol: TCP
  volumes:
    - name: html
      emptyDir: {}